<a href="https://colab.research.google.com/github/xtianu/UPC_DAPR_2026/blob/main/S1/S1.%20Intro_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



---

**Professor:** Christian Mata Miquel

**Subject:** Data Analysis & Pattern Recognition

**Module:** Exploratory Data Analysis

# **S1. INTRODUCTION TO PYTHON PROGRAMMING**

## Why Python?
Python is a high-level programming language that allows you to solve general-purpose problems. It is especially useful in data processing, pattern recognition and artificial intelligence applications. Think of a kind of very powerful programmable scientific calculator.

The objective of this first part of the course is to hace a crash course on Python programming. In the following laboratory sessions you will learn how to use Python in order to do data analysis and machine learning.

## The google Colaboratory platform: Python notebooks

There are a large number of programming environments that allow you to develop programs with Python. The most common ones require the installation in your computer of a complete Python programming platform such as Anaconda (https://www.anaconda.com/, for MacOS and Windows) or WinPython (https://winpython.github.io/, Windows only). These distributions work perfectly fine but require lots of ressources from your personal computers in terms of disk, memory and CPU.

### Google colab
Instead, in the course we will use a google cloud platform called google collaboratory that already has most of the necessary libraries and allows us to work without the need to install anything on our computers:

https://colab.research.google.com/

The only thing it asks us to start working is a gmail google account. In addition, it allows us to run the programs on google servers, which can be very useful when we manipulate large amounts of data.

### Python notebooks
The way to program on this platform are the **Python notebooks**: A notebook is a document that combines text and Python code. A notebook is composed of two different kinds of cells: code cells and text cells. Text cells are used to explain what we do at any given time, and the Python code excutes different code segments that perform different functions.  Here is a brief tutorial of how to get started working with juputer notebooks in Google colab:

https://colab.research.google.com/notebooks/intro.ipynb

The text in the notebooks is written in a simple markdown language called **Markdown**. To have a brief introduction to markdown language just take a look to https://colab.research.google.com/notebooks/markdown_guide.ipynb

## Executing commands

In order to execute a command, you should write it in a **code cell** and execute it by either clicking in the play icon on the left or by the keyboard shortcut Shift+Return.

In [1]:
3 + 4 + 9

16

In [2]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Modules and libraries

Python is a general-purpose programming language, so when we want to use more specific commands (such as statistical operators or string processing operators) we usually need to import them before we can use them. For Scientific Python, one of the most important libraries that we need is **numpy** (Numerical Python, NumPy: Basic mathematical operations with vectors and arrays: https://numpy.org/), which can be loaded like this:

In [3]:
import numpy as np
np.sqrt(25)

np.float64(5.0)

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Access to the functions, variables and classes of a module depends on the way the module was imported:

In [5]:
import math
math.cos(math.pi)

-1.0

In [6]:
import math as m  # import using an alias
m.cos(m.pi)

-1.0

In [7]:
from math import cos,pi # import only some functions
cos(pi)

-1.0

In [8]:
from math import *   # global import
cos(pi)

-1.0

Basides Numpy, the most important in the field of data analysis are the following:

**Scipy**: Basic Statistical Operations: https://www.scipy.org/

**Pandas**: Allows you to manipulate data files in excel, csv, text, etc. https://pandas.pydata.org/

**Seaborn**: Graphing data in pandas format: https://seaborn.pydata.org/

**Matplotlib**: Plotting nnumpy arrays: https://matplotlib.org/

**sckit-learn**: Pattern recognition and artificial intelligence tools https://scikit-learn.org/stable/

**sckit-image**: Image processing https://scikit-image.org/

## Variables
Often the value returned by an operation will be used later on. Values can be stored for later use with the **assignment operator**:

In [9]:
a = 101
type(a)

int

The command has stored the value 101 under the name <code>a</code>. Such stored values are called **objects**.

Making an assignment to an object defines the object. Once an object has been defined, it can be referred to and used in later computations.

To refer to the value stored in the object, just use the object’s name itself. For instance:

In [10]:
np.sqrt(a)

np.float64(10.04987562112089)

In [11]:
a = np.sqrt(a)
a
type(a)

numpy.float64

There are some general rules for object names:

+ Use only letters and numbers and ‘underscores’ (_)
+ Do NOT use spaces anywhere in the name
+ A number cannot be the first character in the name
+ Capital letters are treated as distinct from lower-case letters (i.e., Python is case-sensitive)

For example, this assignation is not valid:

In [16]:
3a = 10

SyntaxError: invalid decimal literal (2547745391.py, line 1)

## Printing out variables:

You can check the value of a variable by printing it. You can also embed the value of the variable in a string using the *format* option of the print instruction:

In [17]:
a = 19
print('The value of a is {}'.format(a))

The value of a is 19

In [18]:
print(a)

19

## Dynamic Typing

When you assign a new value to an existing object (*dynamic typing*), the former values of that object is erased from the computer memory. For instance, we can assign a calue to a variable b:

In [19]:
b = 10.0498756211

but after a new assignment:

In [20]:
b = 'a'
print(b)

a

The value of an object is changed only via the assignment operator. Using an object in a computation does not change the value.

The brilliant thing about organizing operators in terms of input arguments and output values is that the output of one operator can be used as an input to another. This lets complicated computations be built out of simpler ones.

One way to connect the computations is by using objects to store the intermediate outputs:

In [21]:
a = np.arange(5)
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

You can also pass the output of an operator directly as an argument to another operator:

In [22]:
np.sqrt(np.arange(5))

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

Most of the examples used so far have dealt with numbers. But computers work with other kinds of information as well: text, photographs, sounds, sets of data, and so on. The word *type* is used to refer to the kind of information.

It’s important to know about the types of data because operators expect their input arguments to be of specific types. When you use the wrong type of input, the computer might not be able to process your command.

For our purposes, it’s important to distinguish among several basic types:

+ Numeric (positive and negative) data:
    + decimal and fractional numbers (**floats**), <code>a = 3.5</code>
    + arbitrary length whole numbers (**ints**):  <code>c=1809109863596239561236235625629561</code>
+ **Strings** of textual data - you indicate string data to the computer by enclosing the text in quotation marks (e.g., <code>name = "python"</code>).
+ **Boolean** data: <code>a = True</code> or <code>a = False</code>.
+ **Complex** numbers: <code>a = 2+3j</code>
+ Sequence types: **tuples, lists, sets, dictionaries** and **files**.

In [23]:
a = True
type(a)

bool

In [24]:
a = 'a'
print(a)

a

## Operators

+ Addition (also string, tuple and list concatenation) <code>a + b</code>
+ Subtraction (also set difference): <code>a - b</code>
+ Multiplication (also string, tuple and list replication): <code>a * b</code>
+ Division: <code>a / b</code>
+ Truncated integer division (rounded towards minus infinity): <code>a // b</code>
+ Modulus or remainder: <code>a % b</code>
+ Exponentiation: <code>a ** b</code>
+ Assignment: <code>=</code>, <code>-=</code>, <code>+=</code>,<code>/=</code>,<code>*=</code>, <code>%=</code>, <code>//=</code>, <code>**=</code>
+ Boolean comparisons: <code>==</code>, <code>!=</code>, <code><</code>,<code>></code>,<code><=</code>, <code>>=</code>
+ Boolean operators: <code>and</code>, <code>or</code>, <code>not</code>
+ Membership test operators: <code>in</code>, <code>not in</code>
+ Object identity operators: <code>is</code>, <code>is not</code>
+ Bitwise operators (or, xor, and, complement): <code>|</code>, <code>^</code>, <code>&</code>, <code>~</code>
+ Left and right bit shift: <code><<</code>, <code>>></code>

### Python as a calculator

The Python language has a concise notation for arithmetic that looks very much like the traditional one.

In [25]:
a = 3+2
b= 3.5 * -8
c = 10/6
print(a, b, c, 10./6.)

5 -28.0 1.6666666666666667 1.6666666666666667

Some math functions are not available in the basic Python module, and they need to be imported from a specific module:

In [26]:
import math   # this instruction is not executed if the module has already been imported
print(math.pi + math.sin(100) + math.ceil(2.3))

5.635227012480034

### String processing with Python

Strings are list of characters:

In [27]:
a = 'python'
type(a)

str

In [28]:
print("Hello" )

Hello

In [29]:
print("This is 'an example' of the use of quotes and double quotes")
print('This is "another example" of the use of quotes and double quotes')

This is 'an example' of the use of quotes and double quotes
This is "another example" of the use of quotes and double quotes

We can use the operator ``+`` to concatenate strings:

In [30]:
a = 'He'
b = 'llo'
c = a+b+'!'
print(c)

Hello!

Substrings within a string can be accessed using **slicing**. Slicing uses ``[]`` to contain the indices of the characters in a string, where the first index is $0$, and the last is $n - 1$ (assuming the string has $n$ characters).

In [31]:
a = 'Python'
print(a[:], a[0], a[2:], a[:3], a[2:4], a[::2], a[1::2])

Python P thon Pyt th Pto yhn

You can insert the value of a certain variable in a string by using the format option of the pring function:

In [32]:
a= 99.99
print('The value that takes variable a is {}'.format(a))

The value that takes variable a is 99.99

### Conditionals

The conditional structure in Python is **<code>If</code>**. It is usally combined with
relational operators: <code> <, <=, ==, >=, >, != </code>.

In [33]:
def main(celsius):
    fahrenheit = 9.0 /5.0 * celsius + 32
    print("The temperature in Fahrenheit is", fahrenheit)
    if fahrenheit > 90:
        print("It's really hot out there.")
    elif fahrenheit < 30:
        print("It's really cold out there.")
    else: pass

main(35)

The temperature in Fahrenheit is 95.0
It's really hot out there.

### Boolean operators.

In [34]:
a = 4
b = 40
(a>2) and (b>30)

True

In [35]:
(a>5) or (b>100)

False

In [36]:
not(a>2)

False

### Loops

* For
* While

In [37]:
for i in range(0,10,1):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [38]:
i=0
while i < 10 :
    print(i)
    i= i+1

0
1
2
3
4
5
6
7
8
9

In [39]:
vector = ["hola","buenos","dias"]
for palabra in vector:
    print (palabra)

hola
buenos
dias

**``If``** statesments can be combined with **loops** (``for``, ``while``):

In [40]:
numbers = [-5, 3,2,-1,9,6]
total = 0

for n in numbers:
    if n >= 0:
        total += n

print(total)

20

In [41]:
def average(a):
    sum = 0.0
    for i in a:
        sum = sum + i
    return sum/len(a)

average([1,2,3,4])

2.5

In [42]:
def main(n):
    cont = 0
    while (int(n) > 0):
        cont += 1
        n = n/2
#        print n
    return cont-1

main(10)
# main(10.3)

3

## Data types

We need to represent data collections: words in a text, students in a course, experimental data, etc., or to store intermediate results. The most simple data collection is the <code>list</code> (an ordered sequence of objects):

### Numpy Arrays

In data analysis and machine learning, numerical data is often stored in a multidimensional matrix. It is convenient to manage numerical arayys with numpy:

In [43]:
x = np.array([[0, 1], [1, 1], [2, 2]])
x

array([[0, 1],
       [1, 1],
       [2, 2]])

Check the size (rows, columns):

In [44]:
x.shape

(3, 2)

In [45]:
import numpy as np

x = np.array([[0, 1], [1, 1], [2, 2]])

print("The matrix {}".format(x))
print("Alternate take: The Matrix = " + str(x))

print("Shape {}".format(x.shape))

print("Element at Row 0, column 0: {}".format(x[0,0]))

print("Selects the first column of the matrix {}".format(x[:,0]))

print("Selects the first row {}".format(x[0,:]))

print("Transposes the matrix {}".format(x.transpose()))

idx = np.where(x <= 1)
print('indicates position that fulfills condition: {}'.format(idx))

y = np.linspace(0,2,100)

print(y.shape)
print(y[-1])
print(y.T)

The matrix [[0 1]
 [1 1]
 [2 2]]
Alternate take: The Matrix = [[0 1]
 [1 1]
 [2 2]]
Shape (3, 2)
Element at Row 0, column 0: 0
Selects the first column of the matrix [0 1 2]
Selects the first row [0 1]
Transposes the matrix [[0 1 2]
 [1 1 2]]
indicates position that fulfills condition: (array([0, 0, 1, 1]), array([0, 1, 0, 1]))
(100,)
2.0
[0.         0.02020202 0.04040404 0.06060606 0.08080808 0.1010101
 0.12121212 0.14141414 0.16161616 0.18181818 0.2020202  0.22222222
 0.24242424 0.26262626 0.28282828 0.3030303  0.32323232 0.34343434
 0.36363636 0.38383838 0.4040404  0.42424242 0.44444444 0.46464646
 0.48484848 0.50505051 0.52525253 0.54545455 0.56565657 0.58585859
 0.60606061 0.62626263 0.64646465 0.66666667 0.68686869 0.70707071
 0.72727273 0.74747475 0.76767677 0.78787879 0.80808081 0.82828283
 0.84848485 0.86868687 0.88888889 0.90909091 0.92929293 0.94949495
 0.96969697 0.98989899 1.01010101 1.03030303 1.05050505 1.07070707
 1.09090909 1.11111111 1.13131313 1.15151515 1.17171717 1.19191919
 1.21212121 1.23232323 1.25252525 1.27272727 1.29292929 1.31313131
 1.33333333 1.35353535 1.37373737 1.39393939 1.41414141 1.43434343
 1.45454545 1.47474747 1.49494949 1.51515152 1.53535354 1.55555556
 1.57575758 1.5959596  1.61616162 1.63636364 1.65656566 1.67676768
 1.6969697  1.71717172 1.73737374 1.75757576 1.77777778 1.7979798
 1.81818182 1.83838384 1.85858586 1.87878788 1.8989899  1.91919192
 1.93939394 1.95959596 1.97979798 2.        ]

### Lists

Lists are a built-in data type which require other data types to be useful. A list is a collection of other objects – floats, integers, complex numbers, strings or even other lists.

Lists also support slicing to retrieve one or more elements. Basic lists are constructed using square braces, ``[]``, and values are separated using
commas.

In [46]:
l=[]
type(l)

list

In [47]:
x=[1,2,3,4,[1,2,3,4],'jordi']
print(x[4:], x[0], x[5])

[[1, 2, 3, 4], 'jordi'] 1 jordi

In [48]:
x

[1, 2, 3, 4, [1, 2, 3, 4], 'jordi']

In [49]:
x[-2:]  # The stride can also be negative which can be used to select the
        # elements of a list in reverse order.

[[1, 2, 3, 4], 'jordi']

Lists can be multidimensional and slicing can be done directly in higher dimensions:

In [50]:
x = [[1,2,3,4], [5,6,7,8]]
print(x[0], x[1][3])

[1, 2, 3, 4] 8

In [51]:

list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
b = "This is an example".split()
print(b)

['This', 'is', 'an', 'example']

A list is an *ordered, mutable and dynamic* collection of *non-homogeneous* objects:

In [53]:
a = [1,2,3,4]
a[1] = 7
print(a)

[1, 7, 3, 4]

In [54]:
c = a + b
print(c)

[1, 7, 3, 4, 'This', 'is', 'an', 'example']

In [55]:
zeroes = [0] * 10
del zeroes[5:]
print(zeroes)

[0, 0, 0, 0, 0]

In [56]:
zeroes.append(1)
print(zeroes)

[0, 0, 0, 0, 0, 1]

In [57]:
zeroes.remove(1)
print(zeroes)

[0, 0, 0, 0, 0]

In [58]:
if 1 in zeroes:
    print(False)
else:
    print(True)

True

### Dictionaries

A dictionary is a collection that allows the access of an *element* by using a *key*:

In [59]:
dict = {"d": "D", "b":"B", "c":"C"}
dict["d"]

'D'

Dictionaries are *mutable, dynamic* and *unordered*:

In [60]:
dict["a"]="A"
dict

{'d': 'D', 'b': 'B', 'c': 'C', 'a': 'A'}

In [61]:
"a" in dict

True

In [62]:
del dict["a"]
print(dict)

{'d': 'D', 'b': 'B', 'c': 'C'}

In [63]:
dict = {"d": "D", "b":"B", "c":"C"}
dict.items()

dict_items([('d', 'D'), ('b', 'B'), ('c', 'C')])

## A program in Python

General Rules:

+ All text from a <code>#</code> simbol to the end of a line are considered as comments.
+ Code must be **indented** and sometimes delineated by colons. The Python standard for indentation is four spaces. Never use tabs: it can produce hard to find errors. Set you editor to convert tabs to spaces.
+ Typically, a statement must be on a line. You can use a backslash <code>\</code> at the end of a line to continue a statement on to the next line.

In [66]:
# This program computes the factorial of 100.

fact = 1
n= 100
for factor in range(n,0,-1):
    fact = fact * factor
print(fact)

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000

In [67]:
list(range(10,0,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

<div class="alert alert-error"> When we write a colon at the end of an iteration, all lines indented at the next level are considered *part* of the iteration.

When we write a line at the same indentation as the iteration, we are closing the iteration.</div>

## References

We can inspect the reference of an object:

In [68]:
a ='hello'
print(id(a))

138585650217392

Two different objects:

In [69]:
a = [1,2,3]
b = [1,2,3]
print(id(a), id(b))
print (a is b)
print (a == b)

138585100530304 138585100530496
False
True

Object alias:

In [70]:
a = [1,2,3]
b = a                     # alias
print(id(a), id(b))

138585100666368 138585100666368

Cloning:

In [71]:
a = [1,2,3]
b = a[:]                  # cloning with :

print(a, b, b[1:], id(a), id(b), id(b[1:]))

[1, 2, 3] [1, 2, 3] [2, 3] 138585100666752 138585100666496 138585100665152

When a list is an argument of a function, we are sending the *reference*, not a *copy*

## Functions

To create a function, use def.

In [72]:
def head(list):     #parameters separated by comma
    return list[0]  #Identation means inside functions

numbers=[1,2,3,4]
print(head(numbers), numbers)

1 [1, 2, 3, 4]

In [73]:
head(numbers)

1

In [74]:
def change_first_element(list):
    list[0]=0 #it returns none!

numbers=[1,2,3,4]
change_first_element(numbers)

If we return a list we are returning a reference:

In [75]:
def tail(list):
    return list[1:]     # we are creating a new list

numbers=[1,2,3,4]
rest = tail(numbers)
print(rest, numbers)
print(id(rest), id(numbers))

[2, 3, 4] [1, 2, 3, 4]
138585100531072 138585100529920

In [76]:
# Press tab
numbers.reverse()
print(numbers)

[4, 3, 2, 1]

Sometimes it is important to perform a *sanity check* about what is doing a pre-defined function:

In [77]:
numbers=[1,2,3,4]
def test(l):
    return l.reverse() #Reverse return NONE!
print(numbers)
print(numbers, test(numbers)) #Reverses changes the list INPLACE if we don't make a copy we will  alter the original numbers

[1, 2, 3, 4]
[4, 3, 2, 1] None

In [78]:
numbers=[1,2,3,4]

def test(l):
    l.reverse() #Reverse changes the list INPLACE, if we don't make a copy we will  alter the original numbers
    return l

print(numbers, test(numbers))
print(id(numbers), id(test(numbers)))

[4, 3, 2, 1] [4, 3, 2, 1]
138585100679296 138585100679296

In [79]:
numbers=[1,2,3,4]

def test(l):
    a=l[:]
    l.reverse() #Reverse changes the list INPLACE, if we don't make a copy we will alter the original numbers
    return a

print(numbers, test(numbers))
print(id(numbers), id(test(numbers)))

[4, 3, 2, 1] [1, 2, 3, 4]
138585100676096 138585392664704

## Algorithms in Python

#### Factorial

The factorial of a non-negative integer $n$, denoted by $n!$, is the product of all positive integers less than or equal to $n$.

In [81]:
def factorial(n):
    fact = 1
    for factor in range(n,0,-1):
        fact = fact * factor
    return fact

In [82]:
factorial(100)

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000

#### Fibonacci

The Fibonacci Sequence is the series of numbers: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ...

The general rule to compute the sequence is very simple: The next number is found by adding up the two numbers before it.

In [83]:
def fib1(n):
    if n==1:
        return 1
    if n==0:
        return 0
    return fib1(n-1) + fib1(n-2)

fib1(20)

# this function cannot compute fib(100)

6765

In [84]:
def fib2(n):
    a, b = 0, 1
    for i in range(1,n+1):
        a, b = b, a + b
    return a

n = 1000
if n<15:
    print(fib1(n))
else:
    print(fib2(n))

43466557686937456435688527675040625802564660517371780402481729089536555417949051890403879840079255169295922593080322634775209689623239873322471161642996440906533187938298969649928516003704476137795166849228875

#### Greatest Common Divisor

The greatest common divisor of two positive integers $a$ and $b$ is the largest divisor common to $a$ and $b$.  The Euclidean algorithm, or Euclid's algorithm, is an interative method for computing the greatest common divisor of two integers.

+ If $a<b$, exchange $a$ and $b$.
+ Divide $a$ by $b$ and get the remainder, $r$. If $r=0$, report $b$ as the GCD of $a$ and $b$.
+ Replace $a$ by $b$ and replace $b$ by $r$. If $r \neq 0$ iterate.

In [85]:
def gcd(a,b): # Euclides algorithm v1.0: pseudocode translation
    r = 1
    while r != 0:
        if a<b:
            c=a
            a=b
            b=c
        r = a%b
        if r == 0:
            return b
        else:
            a = b
            b = r

gcd(100,16)

4

In [86]:
def gcd(a,b):   # Euclides algorithm v2.0: idiomatic Python
    while a:
        a, b = b%a, a
    return b

gcd(100,16)

4

In [87]:
a = 0
a == False

True

## Reading and handling data

Since we are going to deal with a wide range of data types (text, numerical arrays, images, etc.).

When working with google colab, the first thing you need to do is to grant access to the files in your google drive:

In [88]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

Once you have access to your google drive, the files are available at the folder /content/gdrive. In order to list the folders in the root your drive use the listdir function from the os library:

In [89]:
import os

root_folder = '/content/gdrive/My Drive/'

for kdirs in os.listdir(root_folder):
    if os.path.isdir(os.path.join(root_folder, kdirs)):
        print(kdirs)

Colab Notebooks
TECM
.ipynb_checkpoints
Informes de les reunions
AI
Classroom
UT
Personal
UL
UPC
Desat des de Chrome (1)
HSJD
HSPAU
Desat des de Chrome
IABIOMED
Meet Recordings
VideoRB

If you want to dig into the contents of several folders then use the function walk instead

In [90]:
import os

for root, dirs, files in os.walk(root_folder, topdown=False):
    for name in dirs:
        print(os.path.join(root, name))

/content/gdrive/My Drive/Colab Notebooks/.ipynb_checkpoints
/content/gdrive/My Drive/TECM/Mammography database
/content/gdrive/My Drive/TECM/Curso
/content/gdrive/My Drive/TECM/.ipynb_checkpoints
/content/gdrive/My Drive/Informes de les reunions/2026-05-04 15:59 TFM Lukas
/content/gdrive/My Drive/Informes de les reunions/2026-05-04 16:29 TFM Benedict
/content/gdrive/My Drive/Informes de les reunions/2026-05-04 17:00 TFG Sara
/content/gdrive/My Drive/Informes de les reunions/2026-05-19 08:57 pdo-nyxc-nrn
/content/gdrive/My Drive/Informes de les reunions/2026-05-20 09:08 CV - Tirana 3
/content/gdrive/My Drive/Informes de les reunions/2026-05-20 09:48 CV - Tirana 3
/content/gdrive/My Drive/Informes de les reunions/2026-05-20 10:41 CV - Tirana 3
/content/gdrive/My Drive/Informes de les reunions/2026-05-20 11:29 CV - Tirana 3
/content/gdrive/My Drive/Informes de les reunions/2026-05-26 09:00 TFG Patricia
/content/gdrive/My Drive/Informes de les reunions/2026-05-26 09:31 TFG Mariona
/content/gdrive/My Drive/Informes de les reunions/2026-05-26 10:00 TFG Arann
/content/gdrive/My Drive/Informes de les reunions/2026-05-29 12:11 PIB - Julia Romagosa
/content/gdrive/My Drive/Informes de les reunions/2026-06-15 15:30 Reunió Abel Torres
/content/gdrive/My Drive/Informes de les reunions/2026-06-16 16:00 Francesco
/content/gdrive/My Drive/Informes de les reunions/2026-06-17 10:01 EMSSE Interviews
/content/gdrive/My Drive/Informes de les reunions/2026-06-19 12:32 ANECA
/content/gdrive/My Drive/Informes de les reunions/2026-06-25 11:29 Reunión DAPR
/content/gdrive/My Drive/Informes de les reunions/2026-06-25 12:29 Reunió Abel-Francesco
/content/gdrive/My Drive/Informes de les reunions/2026-06-25 13:01 Reunió Abel-Francesco
/content/gdrive/My Drive/Informes de les reunions/2026-06-25 13:01 Jornada IABIOMED - MS
/content/gdrive/My Drive/Informes de les reunions/2026-07-03 08:56 Defensa TFE MICHAL ZATKALÍK
/content/gdrive/My Drive/Informes de les reunions/2026-07-03 09:52 Defensa TFG Marc Pros Carpintero
/content/gdrive/My Drive/Informes de les reunions/2026-07-03 10:51 Defensa TFG Khushdepp Singh
/content/gdrive/My Drive/Informes de les reunions/2026-07-09 10:16 TFM Lukas Moser
/content/gdrive/My Drive/Informes de les reunions/2026-07-09 11:00 TFM Benedict Martus
/content/gdrive/My Drive/Informes de les reunions/2026-07-10 08:54 TFM Silvi Noçka
/content/gdrive/My Drive/Informes de les reunions/2026-07-10 09:56 TFM Masha Goudarzi
/content/gdrive/My Drive/Informes de les reunions/2026-07-13 11:28 ydz-vyre-cgq
/content/gdrive/My Drive/Informes de les reunions/2026-07-13 11:37 Manel Lozano
/content/gdrive/My Drive/Informes de les reunions/2026-07-15 13:26 rgk-eite-yii
/content/gdrive/My Drive/Informes de les reunions/2026-07-15 14:04 fri-kxqd-qer
/content/gdrive/My Drive/Informes de les reunions/2026-07-15 14:19 bqf-fkiy-jrz
/content/gdrive/My Drive/Informes de les reunions/2026-07-15 14:41 zdo-hwcs-cks
/content/gdrive/My Drive/Informes de les reunions/2026-07-15 14:59 mty-xnvr-tmc
/content/gdrive/My Drive/Informes de les reunions/2026-07-28 09:59 Viatge Tirana
/content/gdrive/My Drive/AI/Segmentation/Prostate
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/ANORMAL/TRANCE_DREPANOCITOSIS_ANORMAL/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/ANORMAL/TRANCE_DREPANOCITOSIS_ANORMAL/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/ANORMAL/TRANCE_DREPANOCITOSIS_ANORMAL
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/INFARTO/TRANCE_INFARTO_ACM_IZDA/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/INFARTO/TRANCE_INFARTO_ACM_IZDA/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/INFARTO/TRANCE_INFARTO_ACM_IZDA_2/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/INFARTO/TRANCE_INFARTO_ACM_IZDA_2/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/INFARTO/TRANCE_INFARTO_ACM_IZDA
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/INFARTO/TRANCE_INFARTO_ACM_IZDA_2
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_4/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_4/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_1/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_1/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_2/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_2/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_3/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_3/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_5/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_5/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_VENA_GALENO/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_VENA_GALENO/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_4
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_1
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_2
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_3
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_5
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV/TRANCE_MAV_VENA_GALENO
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_2_POST_ACETAZOLAMIDA/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_2_POST_ACETAZOLAMIDA/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_1/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_1/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_2_PRE_ACETAZOLAMIDA/2 - FILTRADES/.ipynb_checkpoints
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_2_PRE_ACETAZOLAMIDA/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_2_PRE_ACETAZOLAMIDA/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_5_POST_ACETAZOLAMIDA/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_5_POST_ACETAZOLAMIDA/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_5_POST_ACETAZOLAMIDA_DIAGNOSTICO/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_5_POST_ACETAZOLAMIDA_DIAGNOSTICO/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_5_PRE_ACETAZOLAMIDA/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_5_PRE_ACETAZOLAMIDA/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_5_PRE_ACETAZOLAMIDA_DIAGNOSTICO/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_5_PRE_ACETAZOLAMIDA_DIAGNOSTICO/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_3/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_3/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_4/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_4/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_6/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_6/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_7/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_7/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_8/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_8/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test3_28_11_20/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test3_28_11_20/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test1_27_06_19/pre/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test1_27_06_19/pre/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test1_27_06_19/post/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test1_27_06_19/post/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test1_27_06_19/pre
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test1_27_06_19/post
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test2_15_01_20/post/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test2_15_01_20/post/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test2_15_01_20/pre/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test2_15_01_20/pre/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test2_15_01_20/post
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test2_15_01_20/pre
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test4_17_02_22/pre/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test4_17_02_22/pre/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test4_17_02_22/post/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test4_17_02_22/post/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test4_17_02_22/pre
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test4_17_02_22/post
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test3_28_11_20
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test1_27_06_19
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test2_15_01_20
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9/Test4_17_02_22
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_2_POST_ACETAZOLAMIDA
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_1
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_2_PRE_ACETAZOLAMIDA
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_5_POST_ACETAZOLAMIDA
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_5_POST_ACETAZOLAMIDA_DIAGNOSTICO
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_5_PRE_ACETAZOLAMIDA
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_5_PRE_ACETAZOLAMIDA_DIAGNOSTICO
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_3
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_4
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_6
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_7
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_8
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA/TRANCE_MOYAMOYA_9
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/NORMAL/TRANCE_CEFALEA_NORMAL/2 - FILTRADES
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/NORMAL/TRANCE_CEFALEA_NORMAL/1 - ORIGINALS
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/NORMAL/TRANCE_CEFALEA_NORMAL
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/ANORMAL
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/INFARTO
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MAV
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/MOYAMOYA
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance/NORMAL
/content/gdrive/My Drive/AI/Databases/Trance/Database_Trance
/content/gdrive/My Drive/AI/Databases/Trance
/content/gdrive/My Drive/AI/.ipynb_checkpoints
/content/gdrive/My Drive/AI/Segmentation
/content/gdrive/My Drive/AI/Classification
/content/gdrive/My Drive/AI/Databases
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 2/images/test
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 2/images/medical
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 2/images
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 2/test
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 3/imatges P5/medical
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 3/imatges P5/test
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 3/imatges p6/test
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 3/imatges p6/medical
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 3/imatges P5
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 3/imatges p6
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 4/Exemples de Segmentació/Exemple 1
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 4/Exemples de Segmentació/Exemple2
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 4/Exemples de Segmentació
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 1/images
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 2
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 3
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 4
/content/gdrive/My Drive/Classroom/Template PIB/Challenge
/content/gdrive/My Drive/Classroom/Template PIB/Sessió 1
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 2/Solucions
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 2/Exercicis
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 3/Exemples
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 4/Exemples
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 5/Exercicis
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 7/Repàs
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 9/Exercicis
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 11/ejercicios
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 1/Exemples
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 6/Exercicis
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 2
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 3
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 4
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 5
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 7
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 8
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 9
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 10
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 11
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/test examen
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 1
/content/gdrive/My Drive/Classroom/Template - INFO - Teoria/Sessió 6
/content/gdrive/My Drive/Classroom/Template English - Teoria/S2/Exercises
/content/gdrive/My Drive/Classroom/Template English - Teoria/S3/Examples
/content/gdrive/My Drive/Classroom/Template English - Teoria/S4/Examples
/content/gdrive/My Drive/Classroom/Template English - Teoria/S5/Examples
/content/gdrive/My Drive/Classroom/Template English - Teoria/S6/Exercises
/content/gdrive/My Drive/Classroom/Template English - Teoria/S6/Solucions
/content/gdrive/My Drive/Classroom/Template English - Teoria/S6/Example
/content/gdrive/My Drive/Classroom/Template English - Teoria/S7/Solutions
/content/gdrive/My Drive/Classroom/Template English - Teoria/S9/Exercises
/content/gdrive/My Drive/Classroom/Template English - Teoria/S9/Solutions
/content/gdrive/My Drive/Classroom/Template English - Teoria/S9/Examples
/content/gdrive/My Drive/Classroom/Template English - Teoria/S8/Exercises
/content/gdrive/My Drive/Classroom/Template English - Teoria/S10/Solutions
/content/gdrive/My Drive/Classroom/Template English - Teoria/S10/Exercises
/content/gdrive/My Drive/Classroom/Template English - Teoria/S1
/content/gdrive/My Drive/Classroom/Template English - Teoria/S2
/content/gdrive/My Drive/Classroom/Template English - Teoria/S3
/content/gdrive/My Drive/Classroom/Template English - Teoria/S4
/content/gdrive/My Drive/Classroom/Template English - Teoria/S5
/content/gdrive/My Drive/Classroom/Template English - Teoria/S6
/content/gdrive/My Drive/Classroom/Template English - Teoria/S7
/content/gdrive/My Drive/Classroom/Template English - Teoria/S9
/content/gdrive/My Drive/Classroom/Template English - Teoria/S8
/content/gdrive/My Drive/Classroom/Template English - Teoria/S10
/content/gdrive/My Drive/Classroom/Template info - Lab/S2/Exemple classe
/content/gdrive/My Drive/Classroom/Template info - Lab/S3/Exercicis
/content/gdrive/My Drive/Classroom/Template info - Lab/S3/Solucions
/content/gdrive/My Drive/Classroom/Template info - Lab/S4/Exemples
/content/gdrive/My Drive/Classroom/Template info - Lab/S4/Solucions
/content/gdrive/My Drive/Classroom/Template info - Lab/S4/Exercicis
/content/gdrive/My Drive/Classroom/Template info - Lab/S5/Exercicis
/content/gdrive/My Drive/Classroom/Template info - Lab/S5/Solucions
/content/gdrive/My Drive/Classroom/Template info - Lab/S5/Exemples
/content/gdrive/My Drive/Classroom/Template info - Lab/S6/Exemples
/content/gdrive/My Drive/Classroom/Template info - Lab/S6/Exercicis
/content/gdrive/My Drive/Classroom/Template info - Lab/S6/Solucions
/content/gdrive/My Drive/Classroom/Template info - Lab/S7/Exercicis
/content/gdrive/My Drive/Classroom/Template info - Lab/S7/Exemple
/content/gdrive/My Drive/Classroom/Template info - Lab/S7/Solucions
/content/gdrive/My Drive/Classroom/Template info - Lab/S8/Exercicis
/content/gdrive/My Drive/Classroom/Template info - Lab/S8/Exemples
/content/gdrive/My Drive/Classroom/Template info - Lab/S9/Exercicis
/content/gdrive/My Drive/Classroom/Template info - Lab/S10/Exercicis
/content/gdrive/My Drive/Classroom/Template info - Lab/S10/Solucions
/content/gdrive/My Drive/Classroom/Template info - Lab/S11/Exercicis
/content/gdrive/My Drive/Classroom/Template info - Lab/S12/Exercicis
/content/gdrive/My Drive/Classroom/Template info - Lab/S12/Exemples
/content/gdrive/My Drive/Classroom/Template info - Lab/S12/Solucions
/content/gdrive/My Drive/Classroom/Template info - Lab/S12/deures solucions
/content/gdrive/My Drive/Classroom/Template info - Lab/S1
/content/gdrive/My Drive/Classroom/Template info - Lab/S2

### Accessing shared files

Download the shared folder DAPR sample data from

https://drive.google.com/drive/folders/1zKHhi3ZbhO8lUwtDAOo7qFZJlIVQjqL4?usp=sharing

and place it in the root of your google drive:

Now read the csv file text.csv:

In [94]:
import csv
f = open("/content/gdrive/MyDrive/UPC/Docencia/DAPR/Lab/data content/DAPR sample data/test.csv", 'r')
try:
    reader = csv.reader(f)
    for row in reader:
        print(row)
finally:
    f.close()

['\ufeff10;3']
['13;10']
['16;17']
['19;24']
['22;31']
['25;38']
['28;45']
['31;52']
['34;59']

Writing csv files

In [95]:
import csv

ifile  = open("/content/gdrive/MyDrive/UPC/Docencia/DAPR/Lab/data content/DAPR sample data/test.csv", 'r')
reader = csv.reader(ifile)

ofile  = open('/content/gdrive/MyDrive/UPC/Docencia/DAPR/Lab/data content/DAPR sample data/test1.csv', "w")
writer = csv.writer(ofile, delimiter=',', lineterminator='\n')

for row in reader:
    writer.writerow(row)

ifile.close()
ofile.close()

### Read excel with Pandas

In most cases, we are using the pandas library in order to read data.

In [97]:
import pandas as pd
df = pd.read_excel('/content/gdrive/MyDrive/UPC/Docencia/DAPR/Lab/data content/DAPR sample data/test.xlsx', index_col=0,header=2)
df.head()

            Humans  Robots
Date
2019-03-10      10       3
2019-03-11      13      10
2019-03-12      16      17
2019-03-13      19      24
2019-03-14      22      31

In [98]:
df['Humans']

Date
2019-03-10    10
2019-03-11    13
2019-03-12    16
2019-03-13    19
2019-03-14    22
2019-03-15    25
2019-03-16    28
2019-03-17    31
2019-03-18    34
Name: Humans, dtype: int64

In [99]:
df['Robots'].values

array([ 3, 10, 17, 24, 31, 38, 45, 52, 59])

## Read data from web repository:

We can also access to data stored in a GitHub repository.

For example, in this public gitHub:

https://github.com/montera34/escovid19data/tree/master/data/original

We can download the following CSV file:

**covid19_spain_provincias.csv**

Load updated coronavirus data from https://github.com/datadista/datasets.git

In [118]:
# Use the raw content URL for wget to download the CSV file.
!wget -O covid19_spain_provincias.csv 'https://raw.githubusercontent.com/montera34/escovid19data/master/data/original/covid19_spain_provincias.csv'

--2026-07-30 09:15:18--  https://raw.githubusercontent.com/montera34/escovid19data/master/data/original/covid19_spain_provincias.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 426061 (416K) [text/plain]
Saving to: ‘covid19_spain_provincias.csv’

covid19_spain_provi 100%[===================>] 416.08K  --.-KB/s    in 0.04s

2026-07-30 09:15:18 (10.9 MB/s) - ‘covid19_spain_provincias.csv’ saved [426061/426061]

In [119]:
import pandas as pd

# Read the downloaded CSV file into a pandas DataFrame
df_covid = pd.read_csv('covid19_spain_provincias.csv')

# Display the first few rows of the DataFrame
display(df_covid.head())

,date,province,ccaa,new_cases,PCR,TestAc,activos,hospitalized,hospitalized_accumulated,hospitalized_new,intensive_care,deceased,cases_accumulated,cases_accumulated_PCR,recovered,source_name,source,comments
0,2020-02-10,Barcelona,Cataluña,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transparencia Catalunya,https://analisi.transparenciacatalunya.cat/Sal...,NaN
1,2020-02-20,Barcelona,Cataluña,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transparencia Catalunya,https://analisi.transparenciacatalunya.cat/Sal...,NaN
2,2020-02-27,Asturias,"Asturias, Principado de",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,Ministerio de Sanidad (Datadista);RTVE,Datadista (Ministerio de Sanidad) https://gith...,los activos son de flourish de rtve
3,2020-02-27,"Balears, Illes","Balears, Illes",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Ministerio de Sanidad (Datadista);RTVE,Datadista (Ministerio de Sanidad) https://gith...,los activos son de flourish de rtve
4,2020-02-27,Cantabria,Cantabria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,Ministerio de Sanidad (Datadista);RTVE,Datadista (Ministerio de Sanidad) https://gith...,los activos son de flourish de rtve

## Load built-in datasets:

You can access to built-in databases included in many libraries:

Let's acces, for instance, the mpg cars database included in the graphical libraries seaborn:

In [120]:
import pandas as pd
import seaborn as sns
mpg = sns.load_dataset("mpg")
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [121]:
import pandas as pd

# Replace 'your_file_name.csv' with the actual path to your CSV file
# For example, if you want to read 'ccaa_covid19_fallecidos.csv' from your Google Drive, use that path.
df_csv = pd.read_csv('/content/gdrive/MyDrive/UPC/Docencia/DAPR/Lab/data content/DAPR sample data/covid19_spain_provincias.csv')
# df_csv = pd.read_csv('your_file_name.csv')

# Display the first few rows of the DataFrame
display(df_csv.head())

,date,province,ccaa,new_cases,PCR,TestAc,activos,hospitalized,hospitalized_accumulated,hospitalized_new,intensive_care,deceased,cases_accumulated,cases_accumulated_PCR,recovered,source_name,source,comments
0,2020-02-10,Barcelona,Cataluña,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transparencia Catalunya,https://analisi.transparenciacatalunya.cat/Sal...,NaN
1,2020-02-20,Barcelona,Cataluña,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transparencia Catalunya,https://analisi.transparenciacatalunya.cat/Sal...,NaN
2,2020-02-27,Asturias,"Asturias, Principado de",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,Ministerio de Sanidad (Datadista);RTVE,Datadista (Ministerio de Sanidad) https://gith...,los activos son de flourish de rtve
3,2020-02-27,"Balears, Illes","Balears, Illes",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Ministerio de Sanidad (Datadista);RTVE,Datadista (Ministerio de Sanidad) https://gith...,los activos son de flourish de rtve
4,2020-02-27,Cantabria,Cantabria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,Ministerio de Sanidad (Datadista);RTVE,Datadista (Ministerio de Sanidad) https://gith...,los activos son de flourish de rtve